name: Docker-Build

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  schedule:
    - cron: "0 0 1 * *" # every month

jobs:
  build:
    strategy:
      matrix:
        confluence_version: [ '7.12' ]

    runs-on: ubuntu-latest
    env:
      DOCKER_IMAGE: elcweb/confluence:${{ matrix.confluence_version }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.6.0

      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Confluence ${{ matrix.confluence_version }}
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true 
          context: ./${{ matrix.confluence_version }}
          tags: ${{ env.DOCKER_IMAGE }}
          cache-from: type=registry,ref=${{ env.DOCKER_IMAGE }}
          cache-to: type=inline

